'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Clientes
    Public Property Dni_clientes As Integer
    Public Property Apellido As String
    Public Property Nombre As String
    Public Property Direccion As String
    Public Property Telefono As String
    Public Property Email As String
    Public Property fecha_alta As Nullable(Of Date)
    Public Property Estado_cliente As Nullable(Of Boolean)
    Public Property id_provincia As Nullable(Of Integer)
    Public Property Sexo As String

    Public Overridable Property Provincia As Provincia
    Public Overridable Property Facturas As ICollection(Of Facturas) = New HashSet(Of Facturas)

End Class
