'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DetalleFacturas
    Public Property id_factura As Nullable(Of Integer)
    Public Property id_producto As Nullable(Of Integer)
    Public Property cantidad As Nullable(Of Integer)
    Public Property precio As Decimal
    Public Property subtotal As Decimal
    Public Property id_detalle As Integer

    Public Overridable Property Facturas As Facturas
    Public Overridable Property Productos As Productos

End Class
