'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Empleados
    Public Property dni_empleados As Integer
    Public Property apellido As String
    Public Property nombre As String
    Public Property direccion As String
    Public Property telefono As String
    Public Property fecha_ingreso As Nullable(Of Date)
    Public Property id_provincia As Nullable(Of Integer)
    Public Property estado_emplead As Nullable(Of Boolean)
    Public Property Email As String
    Public Property fecha_Nacimiento As Nullable(Of Date)
    Public Property Sexo As String
    Public Property turno As String

    Public Overridable Property Provincia As Provincia
    Public Overridable Property Usuarios As ICollection(Of Usuarios) = New HashSet(Of Usuarios)

End Class
