'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Provincia
    Public Property Id_provincia As Integer
    Public Property Descripcion As String

    Public Overridable Property Clientes As ICollection(Of Clientes) = New HashSet(Of Clientes)
    Public Overridable Property Empleados As ICollection(Of Empleados) = New HashSet(Of Empleados)
    Public Overridable Property Proveedores As ICollection(Of Proveedores) = New HashSet(Of Proveedores)

End Class
