'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Proveedores
    Public Property id_proveedor As Integer
    Public Property razon_social As String
    Public Property direccion As String
    Public Property telefono As String
    Public Property email As String
    Public Property id_provincia As Nullable(Of Integer)

    Public Overridable Property Productos As ICollection(Of Productos) = New HashSet(Of Productos)
    Public Overridable Property Provincia As Provincia

End Class
